port: 8080
healthCheck:
  port: 9090
  liveness: /actuator/health/liveness
  readiness: /actuator/health/readiness
image:
  name: ghcr.io/square-kr/service-gateway
  version: bc342d42
resources:
  cpu: "250m"
  memory: "512Mi"
secrets:
  - service-gateway
imagePullSecrets:
  - ghcr-pull-secret
