port: 3000
healthCheck:
  liveness: /healthz
  readiness: /readyz
image:
  name: ghcr.io/square-kr/sso-server
  version: "9a8ce9f7"
resources:
  cpu: "250m"
  memory: "512Mi"
secrets:
  - sso-server
imagePullSecrets:
  - ghcr-pull-secret
