port: 8081
healthCheck:
  port: 9090
  liveness: /actuator/health/liveness
  readiness: /actuator/health/readiness
image:
  name: ghcr.io/square-kr/accounts-backend
  version: "15b9647c"
resources:
  cpu: "250m"
  memory: "512Mi"
secrets:
  - accounts-backend
imagePullSecrets:
  - ghcr-pull-secret
