port: 3000
healthCheck:
  liveness: /healthz
  readiness: /readyz
image:
  name: ghcr.io/square-kr/notification-backend
  version: "2dc8da7e"
resources:
  cpu: "250m"
  memory: "512Mi"
secrets:
  - notification-backend
imagePullSecrets:
  - ghcr-pull-secret
