port: 3000
healthCheck:
  liveness: /healthz/liveness
  readiness: /healthz/readiness
image:
  name: ghcr.io/square-kr/notification-backend
  version: "0c54aab3"
resources:
  cpu: "250m"
  memory: "512Mi"
secrets:
  - notification-backend
imagePullSecrets:
  - ghcr-pull-secret
