port: 8080

image:
  name: ghcr.io/square-kr/service-gateway
  version: latest

resources:
  cpu: "250m"
  memory: "1Gi"

secrets:
  - service-gateway

imagePullSecrets:
  - ghcr-pull-secret

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: "50%"