port: 8080
healthCheck:
  port: 9090
  liveness: /actuator/health/liveness
  readiness: /actuator/health/readiness
image:
  name: ghcr.io/square-kr/accounts-backend
  version: "1c5817a6"
resources:
  cpu: "250m"
  memory: "1Gi"
secrets:
  - accounts-backend
imagePullSecrets:
  - ghcr-pull-secret
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
pdb:
  enabled: true
  minAvailable: "50%"
